### ISSUE TITLE
不能任意拖拽啊!!!

### ISSUE THREAD

**Issue by huizai0613** [cxMax/FloatingView#1]
sorry， 之前没维护代码， 更新一波。 拖拽大概懂你意思了。我做出来了 艾特你

**Comment by cxMax** [comment]
@huizai0613 可以任意拖拽了，但拖拽后，监听recyclerView移动的显示隐藏我还没想好如何写优雅点，打算用观察者模式来实现就近隐藏的动画效果，暂时留在这里把，我这周完善。暂时先把max:cx_animation="false" 这个属性设置成false把
